{% set libquadmath_version = [0, 0, 0] %}
{% set libgcc_s_version = [1, 0, 0] %}
{% set chost = macos_machine %}
{% set build_number = 2 %}

{% if gfortran_version == "7.5.0" %}
{% set libgfortran_version = "4.0.0" %}
{% set max_libgfortran_version = "5.0.0.a0" %}
{% set libgfortran_major_version = "4" %}
{% set source_sha = "4f518f18cfb694ad7975064e99e200fe98af13603b47e67e801ba9580e50a07f" %}
{% else %}
{% set libgfortran_version = "5.0.0" %}
{% set max_libgfortran_version = "6.0.0.a0" %}
{% set libgfortran_major_version = "5" %}
{% set source_sha = "5258a9b6afe9463c2e56b9e8355b1a4bee125ca828b8078f910303bc2ef91fa6" %}
{% endif %}

package:
  name: gfortran_impl_osx-64
  version: {{ gfortran_version }}

source:
  url: https://ftp.gnu.org/gnu/gcc/gcc-{{ gfortran_version }}/gcc-{{ gfortran_version }}.tar.gz
  sha256: {{ source_sha }}
  patches:
    - libgcc_macosx_min_version.patch

build:
  number: {{ build_number }}
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - libiconv
    - zlib
    - gmp
    - mpfr
    - isl
    - mpc
    - llvm-openmp >=8.0.0

outputs:
  - name: libgfortran
    version: {{ libgfortran_version }}
    build:
      skip: True  # [not osx]
    requirements:
      run:
        - libgfortran{{ libgfortran_major_version }}

  - name: libgfortran{{ libgfortran_major_version }}
    version: {{ gfortran_version }}
    build:
      skip: True  # [not osx]
      run_exports:
        - libgfortran{{ libgfortran_major_version }} >={{ gfortran_version }}
    files:
      - lib/libgfortran.dylib
      - lib/libgfortran.{{ libgfortran_major_version }}.dylib
      - lib/libgomp.dylib
      - lib/libgomp.{{ libgcc_s_version[0] }}.dylib

      # Including libquadmath for the time
      # being. This will need to be broken
      # out in the long term.
      - lib/libquadmath.dylib
      - lib/libquadmath.{{ libquadmath_version[0] }}.dylib

      # Including libgcc_s for the time
      # being. This will need to be broken
      # out in the long term.
      - lib/libgcc_s.{{ libgcc_s_version[0] }}.dylib
      - lib/libgcc_s_ppc64.{{ libgcc_s_version[0] }}.dylib
      - lib/libgcc_s_x86_64.{{ libgcc_s_version[0] }}.dylib

    requirements:
      host:
        - llvm-openmp >=8.0.0
      run:
        - llvm-openmp >=8.0.0
      run_constrained:
        - {{ pin_subpackage("libgfortran", exact=True) }}

    test:
      commands:
        - test -f "${PREFIX}/lib/libgfortran.dylib"
        - test -f "${PREFIX}/lib/libgfortran.{{ libgfortran_major_version }}.dylib"

        - test -f "${PREFIX}/lib/libgomp.dylib"
        - test -f "${PREFIX}/lib/libgomp.{{ libgcc_s_version[0] }}.dylib"

        - test -f "${PREFIX}/lib/libquadmath.dylib"
        - test -f "${PREFIX}/lib/libquadmath.{{ libquadmath_version[0] }}.dylib"

        - test -f "${PREFIX}/lib/libgcc_s.{{ libgcc_s_version[0] }}.dylib"
        - test -f "${PREFIX}/lib/libgcc_s_ppc64.{{ libgcc_s_version[0] }}.dylib"
        - test -f "${PREFIX}/lib/libgcc_s_x86_64.{{ libgcc_s_version[0] }}.dylib"

  - name: gfortran_impl_osx-64
    version: {{ gfortran_version }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make
      host:
        - libiconv
        - zlib
        - gmp
        - mpfr
        - isl
        - mpc
      run:
        - libgfortran{{ libgfortran_major_version }} >={{ gfortran_version }}  # [osx]
        - isl
        - mpfr
        - mpc
        - gmp
        - zlib
        - libiconv
    files:
      - bin/gfortran   # [osx]
      - bin/{{ chost }}-gfortran

      - libexec/gcc/{{ chost }}/{{ gfortran_version }}/collect2
      - libexec/gcc/{{ chost }}/{{ gfortran_version }}/f951
      - libexec/gcc/{{ chost }}/{{ gfortran_version }}/lto-wrapper
      - lib/libgfortran.spec

      # For -fopenmp
      - lib/libgomp.spec


      # For -ffast-math
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/crtfastmath.o

      # For -static
      - lib/libgfortran.a
      - lib/libgomp.a

      - lib/gcc/{{ chost }}/{{ gfortran_version }}/libgcc.a
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/libgcc_eh.a

      - lib/gcc/{{ chost }}/{{ gfortran_version }}/finclude/**

      # include{,-fixed} may not be needed unless -fopenmp is passed (not sure on that)
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/include-fixed/**
      - lib/gcc/{{ chost }}/{{ gfortran_version }}/include/**

      # Stub libraries
      - lib/libgcc_ext.10.4.dylib
      - lib/libgcc_ext.10.5.dylib

    test:
      script: run_test.sh

about:
  home: http://gcc.gnu.org/
  license: GPL 3 (with GCC Runtime Library Exception 3.1)
  license_family: GPL
  license_file: COPYING3
  summary: Fortran compiler and libraries from the GNU Compiler Collection

extra:
  recipe-maintainers:
    - beckermr
    - isuruf
